theme: ./theme
plugins:
  # - saber-plugin-query-posts
  # - saber-plugin-prismjs
  # - saber-plugin-critical
  # If you want to enable local search:
  # - saber-plugin-search
  - ./transformer-asciidoc
  # - ./transformer-pug
  # - ./transformer-phtml
  # - ./transformer-posthtml
permalinks:
  post: /:year/:month/:day/:slug
  page: /:slug